import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import { corsHeaders } from "https://esm.sh/@supabase/supabase-js@2.95.0/cors";

/**
 * Deal Auto-Progression Cron
 * Automatically moves deals through the pipeline:
 *   sourcing (2h) → negotiation (4h) → execution (2h) → completed (triggers deal-completion)
 * 
 * Also handles:
 * - Auto-generation of deal documents when entering execution
 * - Auto-signing of deal documents after 30 min in execution
 * - Payment reminder re-sends for unpaid invoices (every 48h)
 */

const PHASE_DURATIONS_HOURS: Record<string, { next: string; hours: number }> = {
  sourcing: { next: "negotiation", hours: 2 },
  negotiation: { next: "execution", hours: 4 },
  execution: { next: "completed", hours: 2 },
};

const DOCUMENT_TEMPLATES: Record<string, string[]> = {
  aviation: ["Commission Agreement", "Service Terms", "Delivery Confirmation"],
  medical: ["Treatment Plan Summary", "Consent Form", "Commission Agreement"],
  staffing: ["Placement Fee Agreement", "Employment Contract", "Service Terms"],
  lifestyle: ["Booking Confirmation", "Vendor Agreement", "Commission Agreement"],
  logistics: ["Dispatch Order", "Compliance Document", "Commission Agreement"],
  partnerships: ["Partnership Agreement", "Revenue Share Terms", "Commission Agreement"],
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    const results = {
      deals_progressed: [] as string[],
      deals_completed: [] as string[],
      documents_generated: 0,
      documents_signed: 0,
      invoice_reminders_sent: 0,
      errors: [] as string[],
    };

    // ── 1. Progress deals through phases ──
    for (const [currentStatus, config] of Object.entries(PHASE_DURATIONS_HOURS)) {
      const cutoff = new Date(Date.now() - config.hours * 60 * 60 * 1000).toISOString();

      const { data: deals, error: fetchErr } = await supabase
        .from("deals")
        .select("id, deal_number, user_id, category, updated_at")
        .eq("status", currentStatus)
        .lt("updated_at", cutoff)
        .limit(50);

      if (fetchErr) {
        results.errors.push(`Fetch ${currentStatus}: ${fetchErr.message}`);
        continue;
      }

      if (!deals || deals.length === 0) continue;

      for (const deal of deals) {
        try {
          if (config.next === "completed") {
            // Use the deal-completion function for full pipeline
            const { error: completeErr } = await supabase.functions.invoke("deal-completion", {
              body: { action: "complete", dealId: deal.id },
            });

            if (completeErr) {
              // Fallback: just update status directly
              await supabase
                .from("deals")
                .update({ status: "completed", completed_at: new Date().toISOString() })
                .eq("id", deal.id);
            }

            results.deals_completed.push(deal.deal_number);
          } else {
            await supabase
              .from("deals")
              .update({ status: config.next as any })
              .eq("id", deal.id);

            // When entering execution phase, auto-generate documents if none exist
            if (config.next === "execution") {
              const docsGenerated = await autoGenerateDocuments(supabase, deal, results);
              if (docsGenerated > 0) {
                results.documents_generated += docsGenerated;
              }
            }

            results.deals_progressed.push(`${deal.deal_number}: ${currentStatus} → ${config.next}`);
          }
        } catch (dealErr) {
          results.errors.push(`Deal ${deal.deal_number}: ${dealErr instanceof Error ? dealErr.message : "unknown"}`);
        }
      }
    }

    // ── 2. Auto-sign documents for deals in execution phase (30 min grace) ──
    const signCutoff = new Date(Date.now() - 30 * 60 * 1000).toISOString(); // 30 min
    const { data: unsignedDocs } = await supabase
      .from("deal_documents")
      .select("id, deal_id, title, status, created_at, user_id")
      .in("status", ["draft", "pending", "sent"])
      .lt("created_at", signCutoff)
      .limit(100);

    if (unsignedDocs && unsignedDocs.length > 0) {
      // Verify these belong to deals in execution phase
      const dealIds = [...new Set(unsignedDocs.map(d => d.deal_id))];
      const { data: executionDeals } = await supabase
        .from("deals")
        .select("id")
        .in("id", dealIds)
        .eq("status", "execution");

      const executionDealIds = new Set((executionDeals || []).map(d => d.id));

      for (const doc of unsignedDocs) {
        if (!executionDealIds.has(doc.deal_id)) continue;

        try {
          await supabase
            .from("deal_documents")
            .update({
              status: "signed",
              signed_at: new Date().toISOString(),
              signed_by: "QUANTUS Autonomous Signing Engine",
            })
            .eq("id", doc.id);

          results.documents_signed++;
        } catch (signErr) {
          results.errors.push(`Sign doc ${doc.id}: ${signErr instanceof Error ? signErr.message : "unknown"}`);
        }
      }
    }

    // ── 3. Payment reminder re-sends (unpaid invoices older than 48h) ──
    const reminderCutoff = new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString();
    const { data: unpaidInvoices } = await supabase
      .from("invoices")
      .select("id, deal_id, recipient_email, amount_cents, currency, invoice_number, reminder_count, last_reminder_at")
      .in("status", ["pending", "sent"])
      .or(`last_reminder_at.is.null,last_reminder_at.lt.${reminderCutoff}`)
      .limit(20);

    if (unpaidInvoices && unpaidInvoices.length > 0) {
      for (const invoice of unpaidInvoices) {
        if ((invoice.reminder_count ?? 0) >= 5) continue; // Max 5 reminders

        try {
          if (invoice.recipient_email) {
            await supabase.functions.invoke("send-transactional-email", {
              body: {
                templateName: "payment-reminder",
                recipientEmail: invoice.recipient_email,
                idempotencyKey: `payment-reminder-${invoice.id}-${(invoice.reminder_count ?? 0) + 1}`,
                templateData: {
                  invoiceNumber: invoice.invoice_number,
                  amount: `£${((invoice.amount_cents || 0) / 100).toLocaleString()}`,
                },
              },
            });
          }

          await supabase
            .from("invoices")
            .update({
              reminder_count: (invoice.reminder_count ?? 0) + 1,
              last_reminder_at: new Date().toISOString(),
            })
            .eq("id", invoice.id);

          results.invoice_reminders_sent++;
        } catch (reminderErr) {
          results.errors.push(`Reminder ${invoice.invoice_number}: ${reminderErr instanceof Error ? reminderErr.message : "unknown"}`);
        }
      }
    }

    // ── 4. Smart Follow-Up Escalation (3+ unanswered = escalate) ──
    const { data: unansweredOutreach } = await supabase
      .from("vendor_outreach")
      .select("id, deal_id, vendor_name, follow_up_count, status, user_id")
      .gte("follow_up_count", 3)
      .not("status", "in", '("escalated","completed","responded")')
      .limit(20);

    let escalated = 0;
    if (unansweredOutreach && unansweredOutreach.length > 0) {
      for (const outreach of unansweredOutreach) {
        try {
          await supabase
            .from("vendor_outreach")
            .update({ status: "escalated" })
            .eq("id", outreach.id);

          // Create notification for operator
          if (outreach.user_id) {
            await supabase.from("notifications").insert({
              user_id: outreach.user_id,
              title: `Vendor Escalation — ${outreach.vendor_name || "Unknown"}`,
              body: `${outreach.vendor_name || "A vendor"} has not responded after ${outreach.follow_up_count} follow-ups. Consider phone outreach.`,
              category: "deal",
              severity: "warning",
              action_url: "/outreach",
              metadata: { outreach_id: outreach.id, deal_id: outreach.deal_id },
            });
          }
          escalated++;
        } catch (escErr) {
          results.errors.push(`Escalate ${outreach.id}: ${escErr instanceof Error ? escErr.message : "unknown"}`);
        }
      }
    }

    // ── 5. Log system health ──
    await supabase.from("system_health").insert({
      function_name: "deal-auto-progression",
      event_type: "cron_run",
      severity: results.errors.length > 0 ? "warning" : "info",
      metadata: { ...results, vendors_escalated: escalated },
    });

    console.log("Auto-progression results:", JSON.stringify(results));

    return new Response(JSON.stringify({ success: true, ...results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: unknown) {
    console.error("Auto-progression error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

/**
 * Auto-generate deal documents when a deal enters the execution phase.
 */
async function autoGenerateDocuments(
  supabase: any,
  deal: { id: string; deal_number: string; user_id: string; category: string },
  results: { errors: string[] }
): Promise<number> {
  // Check if documents already exist
  const { data: existing } = await supabase
    .from("deal_documents")
    .select("id")
    .eq("deal_id", deal.id)
    .limit(1);

  if (existing && existing.length > 0) return 0;

  const category = deal.category?.toLowerCase() || "lifestyle";
  const templates = DOCUMENT_TEMPLATES[category] || DOCUMENT_TEMPLATES.lifestyle;
  let count = 0;

  for (const docType of templates) {
    try {
      await supabase.from("deal_documents").insert({
        deal_id: deal.id,
        user_id: deal.user_id,
        document_type: docType.toLowerCase().replace(/\s+/g, "_"),
        title: `${docType} — ${deal.deal_number}`,
        content: `[Auto-generated ${docType} for ${deal.category} deal ${deal.deal_number}]\n\nThis document has been prepared by the QUANTUS Autonomous Engine and will be auto-signed after the review period.`,
        status: "draft",
        fields: {
          deal_number: deal.deal_number,
          category: deal.category,
          generated_by: "auto-progression",
        },
      });
      count++;
    } catch (docErr) {
      results.errors.push(`Doc gen ${docType} for ${deal.deal_number}: ${docErr instanceof Error ? docErr.message : "unknown"}`);
    }
  }

  return count;
}
